package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2013-FEB-03  11:31:35 PM
 */
public class one extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for one.
    */
    public one() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(false);
        setFileName("one.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

